<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>unordered list Warehouse</name>
   <tag></tag>
   <elementGuidId>301b13c1-32d4-4904-b01f-31e334c3c462</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='free-solo-2-demo-listbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#free-solo-2-demo-listbox</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'free-solo-2-demo-listbox' and (text() = 'SDA-AL - SDA-Alta RungkutSDA-BA - SDA-BAISDA-CT - SDA-CentreSDA-CU - SDA-CustomerSDA-EX - SDA-ExpiredSDA-KA - SDA-Kiat AnandaSDA-KN - SDA-KonsinyasiSDA-MG - SDA-MGM BoscoSDA-PD - SDA-Packing DrySDA-PF - SDA-Packing FrozenSDA-PL - SDA-PlatinumSDA-PP - SDA-Puncak Darmo PermaiSDA-RT - SDA-ReturSDA-SM - SDA-Susanti MegahSDA-ST - SDA-Sumatraco' or . = 'SDA-AL - SDA-Alta RungkutSDA-BA - SDA-BAISDA-CT - SDA-CentreSDA-CU - SDA-CustomerSDA-EX - SDA-ExpiredSDA-KA - SDA-Kiat AnandaSDA-KN - SDA-KonsinyasiSDA-MG - SDA-MGM BoscoSDA-PD - SDA-Packing DrySDA-PF - SDA-Packing FrozenSDA-PL - SDA-PlatinumSDA-PP - SDA-Puncak Darmo PermaiSDA-RT - SDA-ReturSDA-SM - SDA-Susanti MegahSDA-ST - SDA-Sumatraco')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-listbox-karSnQ gTLFJM MuiAutocomplete-listbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>free-solo-2-demo-listbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>free-solo-2-demo-label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SDA-AL - SDA-Alta RungkutSDA-BA - SDA-BAISDA-CT - SDA-CentreSDA-CU - SDA-CustomerSDA-EX - SDA-ExpiredSDA-KA - SDA-Kiat AnandaSDA-KN - SDA-KonsinyasiSDA-MG - SDA-MGM BoscoSDA-PD - SDA-Packing DrySDA-PF - SDA-Packing FrozenSDA-PL - SDA-PlatinumSDA-PP - SDA-Puncak Darmo PermaiSDA-RT - SDA-ReturSDA-SM - SDA-Susanti MegahSDA-ST - SDA-Sumatraco</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;free-solo-2-demo-listbox&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='free-solo-2-demo-listbox']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'free-solo-2-demo-listbox', '&quot;', ')')])[1]/following::ul[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::ul[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul</value>
   </webElementXpaths>
</WebElementEntity>
