<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Test suite ini berisi Test Cases yang ada pada folder Login</description>
   <name>Login_Module</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>cb2ca152-ccb8-4f1b-9852-d34413231fd9</testSuiteGuid>
   <testCaseLink>
      <guid>68d7ea44-b9c9-4d91-91fc-97bab637184b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC1_ValidCredential</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6c604a8-8e73-44b7-a879-1db6a8034be5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f397cffe-7a3e-4cf0-b114-dff41ef93412</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6214225d-878f-43b0-9cae-1601b29f77fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23e6fea5-1096-49e1-a78b-d13bc0ebbf7e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5becab84-4fba-4dbd-822a-80f2765ec204</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC2_InvalidCredential</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>545391a9-d65a-4133-887a-e2296037c989</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6d398db-5e29-49e0-b695-44456aac114a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>139aaa3d-d5cc-4973-8a68-09440db08046</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f375f56f-b9c3-4751-9c51-035478884894</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73f749a6-0c3a-45bb-8e34-c201099eb9cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC3_Password_NULL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>545391a9-d65a-4133-887a-e2296037c989</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6d398db-5e29-49e0-b695-44456aac114a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>139aaa3d-d5cc-4973-8a68-09440db08046</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f375f56f-b9c3-4751-9c51-035478884894</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>93d1f013-d375-4c9e-9549-2919b43aff93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC4_Username_NULL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdf518ec-aabe-445a-b37d-3e5fb8f04330</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f57d22be-9230-48b1-8548-9ecba6492f12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5da220f9-c729-4ea7-bd06-e99bfb51c322</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38166465-78cf-4235-a26f-079057aa8a7b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6e123026-7eea-4f45-ab4a-4a88418071fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC5_Invalid_Password</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a64328b0-7ac3-4b38-afd3-7a832676a029</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28fd41e5-5566-4501-96fb-cad0ee602d50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6155ca76-ebc5-4409-b939-f79954a48c1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f2c9ddf-f6a5-4dc6-bffc-a81c88b85213</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41b06b64-2166-4b74-ada0-4a4f38ba35d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC6_Invalid_Username</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc067464-4258-45e6-bdda-ac5eb0117f99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4699c77c-5beb-4063-a290-17f8a87bd6ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>044115c6-92ab-477b-b99e-895fa812dad7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10cf2121-0a3a-4d16-afe0-7979025cfa65</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ea60efe-fa84-4aa9-9766-aebd17c37627</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC7_WithoutData</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90d40652-fd1a-49f4-b195-fa59ded87393</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1f9ad81-e167-4bca-9793-ce43b82a4791</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6232eca-0937-4653-8dca-7dfb7e2c7847</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1c15338-dfc9-464e-bae9-c9277663ff3c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34d9b6eb-c686-4da0-80da-3e621ae4b6c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TC8_ForgotPassword</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90d40652-fd1a-49f4-b195-fa59ded87393</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1f9ad81-e167-4bca-9793-ce43b82a4791</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6232eca-0937-4653-8dca-7dfb7e2c7847</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1c15338-dfc9-464e-bae9-c9277663ff3c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
