<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Transfer Cabang</name>
   <tag></tag>
   <elementGuidId>af038070-e7f2-4792-a5c7-8f86d3e728ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.MuiButtonBase-root-JTLGk.dZKzHU.MuiListItemButton-root.MuiListItemButton-gutters.MuiButtonBase-root.MuiListItemButton-root-fsdFYG.dcremC.sc-iwyWTf.iqwCOc.active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/ul/div/div/div[6]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = '/transfer-cabang' and (text() = 'Transfer Cabang' or . = 'Transfer Cabang')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>depth</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root-JTLGk dZKzHU MuiListItemButton-root MuiListItemButton-gutters MuiButtonBase-root MuiListItemButton-root-fsdFYG dcremC sc-iwyWTf iqwCOc active</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/transfer-cabang</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transfer Cabang</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-eggMyH jIKtRA&quot;]/div[@class=&quot;sc-cTkxnA fPMZzy&quot;]/div[@class=&quot;PrivateHiddenCss-root-grrHiC cEwbjk PrivateHiddenCss-root PrivateHiddenCss-mdDown&quot;]/div[@class=&quot;MuiDrawer-docked-dhaOSA IWdmw MuiDrawer-root MuiDrawer-docked sc-hiSbEG jBQbDQ&quot;]/div[@class=&quot;MuiPaper-root-jqRKNJ eXdCVo MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 MuiDrawer-paper-kCJShs jJZlcR MuiDrawer-paper MuiDrawer-paperAnchorLeft MuiDrawer-paperAnchorDockedLeft&quot;]/div[@class=&quot;scrollbar-container sc-kLgnNl jcmrOa ps ps--active-y&quot;]/ul[@class=&quot;MuiList-root-fLynYd kfmrtl MuiList-root&quot;]/div[@class=&quot;sc-iktFfs RvskG&quot;]/div[1]/div[6]/a[@class=&quot;MuiButtonBase-root-JTLGk dZKzHU MuiListItemButton-root MuiListItemButton-gutters MuiButtonBase-root MuiListItemButton-root-fsdFYG dcremC sc-iwyWTf iqwCOc active&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/ul/div/div/div[6]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer Kuota'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mutation Allocated Kuota'])[1]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adjustment Kuota'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/transfer-cabang')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a</value>
   </webElementXpaths>
</WebElementEntity>
