<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link Mutation Allocated Kuota</name>
   <tag></tag>
   <elementGuidId>9e2b01e8-626d-422c-880c-9d00d2c61c87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/ul/div/div/div[12]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>depth</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root-JTLGk dZKzHU MuiListItemButton-root MuiListItemButton-gutters MuiButtonBase-root MuiListItemButton-root-fsdFYG dcremC sc-iwyWTf iqwCOc</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mutation-allocated-kuota</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mutation Allocated Kuota</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-eggMyH jIKtRA&quot;]/div[@class=&quot;sc-cTkxnA fPMZzy&quot;]/div[@class=&quot;PrivateHiddenCss-root-grrHiC cEwbjk PrivateHiddenCss-root PrivateHiddenCss-mdDown&quot;]/div[@class=&quot;MuiDrawer-docked-dhaOSA IWdmw MuiDrawer-root MuiDrawer-docked sc-hiSbEG jBQbDQ&quot;]/div[@class=&quot;MuiPaper-root-jqRKNJ eXdCVo MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 MuiDrawer-paper-kCJShs jJZlcR MuiDrawer-paper MuiDrawer-paperAnchorLeft MuiDrawer-paperAnchorDockedLeft&quot;]/div[@class=&quot;scrollbar-container sc-kLgnNl jcmrOa ps ps--active-y&quot;]/ul[@class=&quot;MuiList-root-fLynYd kfmrtl MuiList-root&quot;]/div[@class=&quot;sc-iktFfs RvskG&quot;]/div[1]/div[12]/a[@class=&quot;MuiButtonBase-root-JTLGk dZKzHU MuiListItemButton-root MuiListItemButton-gutters MuiButtonBase-root MuiListItemButton-root-fsdFYG dcremC sc-iwyWTf iqwCOc&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/ul/div/div/div[12]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer Cabang'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allocated Kuota'])[1]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer Kuota'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/mutation-allocated-kuota')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/a</value>
   </webElementXpaths>
</WebElementEntity>
