<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logo PL Dashboard</name>
   <tag></tag>
   <elementGuidId>555800ca-ca53-4a6a-b6e7-ab266bb73db3</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.MuiAvatar-img.css-1hy9t21</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@alt = 'Lucy' and @src = '/static/img/PL-logo.png']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Lucy</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/img/PL-logo.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAvatar-img css-1hy9t21</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-eggMyH jIKtRA&quot;]/div[@class=&quot;sc-cTkxnA fPMZzy&quot;]/div[@class=&quot;PrivateHiddenCss-root-grrHiC cEwbjk PrivateHiddenCss-root PrivateHiddenCss-mdDown&quot;]/div[@class=&quot;MuiDrawer-docked-dhaOSA IWdmw MuiDrawer-root MuiDrawer-docked sc-hiSbEG jBQbDQ&quot;]/div[@class=&quot;MuiPaper-root-jqRKNJ eXdCVo MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 MuiDrawer-paper-kCJShs jJZlcR MuiDrawer-paper MuiDrawer-paperAnchorLeft MuiDrawer-paperAnchorDockedLeft&quot;]/a[@class=&quot;MuiButtonBase-root-JTLGk dZKzHU MuiListItemButton-root MuiListItemButton-gutters MuiButtonBase-root MuiListItemButton-root-fsdFYG dcremC sc-gWHigU bKZMmY active&quot;]/div[@class=&quot;MuiAvatar-root MuiAvatar-circular sc-jcVcSv jqUarz css-3i9vrz&quot;]/img[@class=&quot;MuiAvatar-img css-1hy9t21&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/a/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Lucy']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
   </webElementXpaths>
</WebElementEntity>
